server:
  port: 4000
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: atguigu-crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 182.42.116.132
    port: 6379
    password: cjs94dsg
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
short:
  message:
    app-code: 61f2eaa3c43e42ad82c26fbbe1061311
    host: https://feginesms.market.alicloudapi.com
    method: GET
    path: /codeNotice
    sign: 151003
    skin: 84683
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
