server:
  port: 7000
spring:
  application:
    name: atguigu-feign-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka/
feign:
  hystrix:
    enabled: true