server:
  port: 80

spring:
  application:
    name: atguigu-crowd-zuul

  session:
    store-type: redis

  redis:
    host: 182.42.116.132
    port: 6379
    password: cjs94dsg
    jedis:
      pool:
        max-idle: 100

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1000/eureka

zuul:
  ignored-services: "*"
  sensitive-headers: "*"  # 在Zuul向其他微服务重定向时保持原本头信息（请求头、响应头）
  routes:
    crowd-portal:
      service-id: atguigu-crowd-auth
      path: /** # 这里一定要使用两个“*”号，不然“/”路径后面的多层路径将无法访问
    crowd-project:
      service-id: atguigu-crowd-project
      path: /project/**
    crowd-order:
      service-id: atguigu-crowd-order
      path: /order/**
    crowd-pay:
      service-id: atguigu-crowd-pay
      path: /pay/**

  # 此处解决后端服务重定向导致用户浏览的 host 变成 后端服务的 host 问题
  add-host-header: true

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000